name: test
on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    run: |
      echo "Slug variables"
      echo $${{ GITHUB_REF }}
      echo http://${{ GITHUB_REF }}.app.facta.io
