name: test
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Do
        run: |
          echo "Slug variables"
          echo $${{ github.ref }}
          echo http://${{ github.ref }}.lel
          echo http://${{ env.GITHUB_REF_SLUG }}.lel
